# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Comments
version:      0.01
version_from: lib/File/Comments.pm
installdirs:  site
requires:
    Archive::Tar:                  0
    Log::Log4perl:                 0
    Module::Pluggable:             0
    Pod::Parser:                   0
    Sysadm::Install:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
