# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Comments
version:      0.05
version_from: lib/File/Comments.pm
installdirs:  site
requires:
    Archive::Tar:                  1.22
    HTML::TokeParser:              2.28
    Log::Log4perl:                 0.5
    Module::Pluggable:             2.4
    Pod::Parser:                   1.14
    PPI:                           0.902
    Sysadm::Install:               0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
